#!/usr/bin/env python3
"""Regenerate profiles/<sector>.json: the S&P 500 by sector, plus Nasdaq-100 and Dow 30
names that are not in the S&P 500, each placed in its sector.

- S&P 500 by sector: the 11 SPDR Select Sector ETFs hold exactly the S&P 500 by GICS
  sector, so each profile scans its ETF's holdings live every run (universe_etfs).
- Nasdaq-100: Nasdaq's list API. Dow 30: SPDR DIA holdings. Names in neither the S&P
  nor the health-care default go into the matching profile's extra_tickers, with
  the sector taken from Yahoo.
- Health care is not a profile here: the default config (XBI/XPH/XHE/XHS/XLV) already
  covers it more broadly. Health-care names from the Nasdaq-100 or Dow that are
  missing from it are printed so they can be added by hand.

Run occasionally (index changes are quarterly):  .venv/bin/python profiles/build_profiles.py
"""
import io, json, re, sys, urllib.request
from pathlib import Path

import pandas as pd
import yfinance as yf

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
CFG = json.loads((ROOT / "config.json").read_text())
SSGA = CFG["universe_url_template"]
UA = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/131.0 Safari/537.36", "Accept": "application/json"}

# profile key: (SPDR ETF, title, emoji, Yahoo sector name)
SECTORS = {
    "technology": ("XLK", "Technology", "💻", "Technology"),
    "communication": ("XLC", "Communication services", "📡", "Communication Services"),
    "consumer-discretionary": ("XLY", "Consumer discretionary", "🛍️", "Consumer Cyclical"),
    "consumer-staples": ("XLP", "Consumer staples", "🛒", "Consumer Defensive"),
    "financials": ("XLF", "Financials", "🏦", "Financial Services"),
    "industrials": ("XLI", "Industrials", "🏭", "Industrials"),
    "energy": ("XLE", "Energy", "🛢️", "Energy"),
    "materials": ("XLB", "Materials", "⛏️", "Basic Materials"),
    "utilities": ("XLU", "Utilities", "💡", "Utilities"),
    "real-estate": ("XLRE", "Real estate", "🏢", "Real Estate"),
}


def holdings(etf):
    raw = urllib.request.urlopen(urllib.request.Request(SSGA.format(etf=etf.lower()), headers={"User-Agent": "Mozilla/5.0"}),
                                 timeout=30).read()
    df = pd.read_excel(io.BytesIO(raw), header=4)
    return {str(t).strip().replace(".", "-") for t in df["Ticker"].dropna()
            if re.fullmatch(r"[A-Z]+(\.[A-Z])?", str(t).strip())}


def nasdaq100():
    j = json.loads(urllib.request.urlopen(urllib.request.Request(
        "https://api.nasdaq.com/api/quote/list-type/nasdaq100", headers=UA), timeout=30).read())
    return {r["symbol"].replace(".", "-") for r in j["data"]["data"]["rows"]}


def main():
    sp = {k: holdings(v[0]) for k, v in SECTORS.items()}
    hc_default = set()
    for spec in CFG["universe_etfs"]:
        hc_default |= holdings(spec["etf"])
    hc_default |= set(CFG["extra_tickers"])
    in_sp = set().union(*sp.values()) | holdings("XLV")
    others = (nasdaq100() | holdings("DIA")) - in_sp - hc_default
    print(f"S&P 500 via SPDR sectors: {len(in_sp)} names; Nasdaq-100/Dow names outside it: {sorted(others)}")
    by_yahoo = {v[3]: k for k, v in SECTORS.items()}
    extras = {k: [] for k in SECTORS}
    for t in sorted(others):
        try:
            sec = yf.Ticker(t).info.get("sector")
        except Exception:
            sec = None
        if sec == "Healthcare":
            print(f"  {t}: health care, not in the default universe; add to config.json extra_tickers")
        elif sec in by_yahoo:
            extras[by_yahoo[sec]].append(t)
            print(f"  {t} -> {by_yahoo[sec]}")
        else:
            print(f"  {t}: no sector from Yahoo ({sec}); skipped")
    for k, (etf, title, emoji, _) in SECTORS.items():
        prof = {
            "_comment": "Generated by profiles/build_profiles.py. The ETF holdings are fetched live each run; "
                        "extra_tickers are Nasdaq-100/Dow names outside the S&P 500 in this sector, plus the ETF.",
            "title": f"{title} IV",
            "emoji": emoji,
            "universe_desc": f"S&P 500 {title.lower()} (SPDR {etf} holdings) plus Nasdaq-100 and Dow names in the "
                             f"sector that are not in the S&P 500",
            "universe_etfs": [{"etf": etf, "sector": title}],
            "extra_tickers": sorted(extras[k]) + [etf],
            "extra_sector": title,
        }
        (HERE / f"{k}.json").write_text(json.dumps(prof, indent=2, ensure_ascii=False) + "\n")
        print(f"{k}: {len(sp[k])} S&P + {len(extras[k])} extra")


if __name__ == "__main__":
    sys.exit(main())
